### ISSUE TITLE
Demos print "not optimized" messages - meaning?

### ISSUE THREAD

**Issue by ashwinvis** [spectralDNS/spectralDNS#25]
Just to be clear I am trying to use the spectralDNS stack without `conda`. That is just using `pip` and `git`. Here is the script I used to install it. 

```bash
#!/bin/bash
mkdir spectralDNS
cd spectralDNS
virtualenv -p python2 --system-site-packages spectraldns_python
source spectraldns_python/bin/activate

pip install pytest nodepy mpi4py cython numpy pythran numba

git clone https://github.com/spectralDNS/mpiFFT4py.git
cd mpiFFT4py
python setup.py install
cd ..

git clone https://github.com/spectralDNS/mpi4py-fft.git
cd mpi4py-fft
python setup.py install
cd ..

git clone https://github.com/drwells/pyFFTW.git
cd pyFFTW
git checkout r2r-try-two
python setup.py install
cd ..

git clone https://github.com/spectralDNS/shenfun.git
cd shenfun
python setup.py install
cd ..

git clone https://github.com/spectralDNS/spectralDNS.git
cd spectralDNS
python setup.py install

cd tests
pytest -v
```

All tests pass. So things seem to be OK. Now that we are on the same page. When I go to `demo` and run 

```bash
$ python TG2D.py NS2D
/usr/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
cross1 not optimized
cross2 not optimized
RK4 not optimized
ForwardEuler not optimized
AB2 not optimized
add_pressure_diffusion not optimized
qt5ct: using qt5ct plugin
Time = 3.67817997932
Fastest = (0.0014629364013671875, 0.2861480712890625)
Slowest = (0.0014629364013671875, 0.2861480712890625)
Error 1.07136521876e-14
```
How can I optimize them? Am I missing some step in the installation? I am not familiar with `numba` and I don't see any compiled numba files.

P.S.: You might want to futurize https://github.com/spectralDNS/spectralDNS/blob/master/demo/refinement_test.py#L27. That is the reason I ended up going back to python 2.7 to try things safely.

**Comment by mikaem** [comment]
Hi
For optimization use 
`    python TG2D.py --optimization cython NS2D`

**Comment by ashwinvis** [comment]
Did that but I am still getting those messages. Normal?

```
(spectraldns) spectralDNS/demo » python TG2D.py --optimization cython NS2D
/usr/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
cross1 not optimized
cross2 not optimized
RK4 not optimized
ForwardEuler not optimized
AB2 not optimized
add_pressure_diffusion not optimized
qt5ct: using qt5ct plugin
Time = 4.01612710953
Fastest = (0.0014700889587402344, 0.29189586639404297)
Slowest = (0.0014700889587402344, 0.29189586639404297)
Error 1.07136521876e-14
(spectraldns) spectralDNS/demo » python TG2D.py --optimization numba NS2D 
/usr/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
cross1 not optimized
cross2 not optimized
RK4 not optimized
ForwardEuler not optimized
AB2 not optimized
add_pressure_diffusion not optimized
qt5ct: using qt5ct plugin
Time = 3.99246501923
Fastest = (0.001466989517211914, 0.2776319980621338)
Slowest = (0.001466989517211914, 0.2776319980621338)
Error 1.07136521876e-14
```

**Comment by ashwinvis** [comment]
I uninstalled all spectralDNS/* packages, deleted all related repos and started from the top. This time installing with a `python setup.py build_ext -i` step in between. Still getting the same "*not optimized*" messages when I run the demo.

Here is the list of all `*.so` files built:
```
(spectraldns) spectDNS/spectralDNS » find -name '*.so'
./spectralDNS/optimization/cython_single_integrators.so
./spectralDNS/optimization/cython_double_integrators.so
./spectralDNS/optimization/cython_single_maths.so
./spectralDNS/optimization/cython_double_maths.so
./spectralDNS/optimization/cython_single_solvers.so
./spectralDNS/optimization/cython_double_solvers.so
./spectralDNS/optimization/pythran_maths.so
./spectralDNS/shen/LUsolve.so
./spectralDNS/shen/Matvec.so
./build/lib.linux-x86_64-2.7/spectralDNS/shen/LUsolve.so
./build/lib.linux-x86_64-2.7/spectralDNS/shen/Matvec.so
./build/lib.linux-x86_64-2.7/spectralDNS/optimization/cython_single_integrators.so
./build/lib.linux-x86_64-2.7/spectralDNS/optimization/cython_double_integrators.so
./build/lib.linux-x86_64-2.7/spectralDNS/optimization/cython_single_maths.so
./build/lib.linux-x86_64-2.7/spectralDNS/optimization/cython_double_maths.so
./build/lib.linux-x86_64-2.7/spectralDNS/optimization/cython_single_solvers.so
./build/lib.linux-x86_64-2.7/spectralDNS/optimization/cython_double_solvers.so
./build/lib.linux-x86_64-2.7/spectralDNS/optimization/pythran_maths.so
```

Is that all or is something missing?

**Comment by mikaem** [comment]
Can you try `python TG.py --optimization cython NS` instead?

**Comment by ashwinvis** [comment]
Similar behaviour. Output:

```
(spectraldns) spectralDNS/demo » python TG.py --optimization cython NS
/usr/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
cross1 not optimized
cross2 not optimized
RK4 not optimized
ForwardEuler not optimized
AB2 not optimized
add_pressure_diffusion not optimized
qt5ct: using qt5ct plugin
0.02 0.124990625221 0.374987498403 0.124990625221
0.04 0.124981250365 0.375006236792 0.124981250365
0.06 0.124971874649 0.37505621344 0.124971874649
0.08 0.124962497294 0.375137437929 0.124962497294
0.1 0.124953117517 0.375249931114 0.124953117517
Time = 1.78541994095
Fastest = (0.02390003204345703, 0.4853639602661133)
Slowest = (0.02390003204345703, 0.4853639602661133)
Memory usage                    RSS accum     RSS total   Virtual  Virtual total
End                                247 MB        247 MB       1267 MB       1267 MB
```

**Comment by mikaem** [comment]
What do you get with `from spectralDNS.optimization import cython_double`?

**Comment by ashwinvis** [comment]
```python
In [1]: from spectralDNS.optimization import cython_double
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-0a254224402a> in <module>()
----> 1 from spectralDNS.optimization import cython_double

build/bdist.linux-x86_64/egg/spectralDNS/optimization/cython_double.py in <module>()

ImportError: No module named cython_double_mpi
```

**Comment by mikaem** [comment]
Ah, my mistake. Looks like I have forgotten to add a file to the repository. You can in the meantime disable by commenting out 'from .cython_single_mpi import *' from 'cython_single.py' and 'from .cython_double_mpi import *' from  'cython_double.py'.

**Comment by ashwinvis** [comment]
Thanks, fingers crossed for those files, sounds like those are important if I want to run spectralDNS with MPI efficiently.

So I tried again. NS solver works, NS2D doesn't.

```
(spectraldns) spectralDNS/demo » python TG2D.py --optimization cython NS2D
/usr/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "TG2D.py", line 66, in <module>
    solve(sol, context)
  File "build/bdist.linux-x86_64/egg/spectralDNS/__init__.py", line 89, in solve
  File "build/bdist.linux-x86_64/egg/spectralDNS/maths/integrators.py", line 188, in func
  File "build/bdist.linux-x86_64/egg/spectralDNS/optimization/__init__.py", line 40, in wrapped_function
  File "spectralDNS/optimization/cython_double_integrators.pyx", line 126, in spectralDNS.optimization.cython_double_integrators.RK4_2D
  File "build/bdist.linux-x86_64/egg/spectralDNS/solvers/NS.py", line 236, in ComputeRHS
  File "build/bdist.linux-x86_64/egg/spectralDNS/solvers/NS2D.py", line 84, in Conv
  File "build/bdist.linux-x86_64/egg/spectralDNS/optimization/__init__.py", line 40, in wrapped_function
  File "spectralDNS/optimization/cython_double_maths.pyx", line 108, in spectralDNS.optimization.cython_double_maths.__pyx_fused_cpdef
TypeError: No matching signature found
(spectraldns) spectralDNS/demo » python TG.py --optimization cython NS    
/usr/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
qt5ct: using qt5ct plugin
0.02 0.124990625221 0.374987498403 0.124990625221
0.04 0.124981250365 0.375006236792 0.124981250365
0.06 0.124971874649 0.37505621344 0.124971874649
0.08 0.124962497294 0.375137437929 0.124962497294
0.1 0.124953117517 0.375249931114 0.124953117517
Time = 1.53042316437
Fastest = (0.01424098014831543, 0.4196147918701172)
Slowest = (0.01424098014831543, 0.4196147918701172)
Memory usage                    RSS accum     RSS total   Virtual  Virtual total
End                                247 MB        247 MB       1276 MB       1276 MB
```

**Comment by mikaem** [comment]
It looks like optimization is broken for the 2D solver. I can see that the cross2 method has not been updated for the latest version that is using lists for wavenumbers instead of numpy arrays. It should be easily fixed, but until then you can either remove the @optimizer decorator for that function in 'maths/cross.py', but that will also turn it off for the 3D case. I'll try to fix it as soon as possible.

**Comment by BuilderOZ** [comment]
when I try  mpirun -np 4 python TG.py VV,the output is 
cross1 not optimized
cross2 not optimized
RK4 not optimized
ForwardEuler not optimized
AB2 not optimized
add_pressure_diffusion not optimized
add_linear not optimized
cross1 not optimized
cross2 not optimized
RK4 not optimized
ForwardEuler not optimized
AB2 not optimized
add_pressure_diffusion not optimized
add_linear not optimized
cross1 not optimized
cross2 not optimized
RK4 not optimized
ForwardEuler not optimized
AB2 not optimized
add_pressure_diffusion not optimized
add_linear not optimized
0.02 0.12499063 0.00000000e+00 7.33260344e-40
0.04 0.12498125 0.00000000e+00 1.53144860e-38
0.06 0.12497187 0.00000000e+00 4.33210638e-38
0.08 0.12496250 0.00000000e+00 1.87003352e-37
0.10 0.12495312 2.77555756e-17 4.50612251e-37
Time = 5.536710739135742
Fastest = (0.01776123046875, 4.074525356292725)
Slowest = (0.017772197723388672, 4.074550151824951)
Memory usage                    RSS accum     RSS total   Virtual  Virtual total
End                                752 MB        752 MB      11724 MB      11724 MB
cross1 not optimized
cross2 not optimized
RK4 not optimized
ForwardEuler not optimized
AB2 not optimized
add_pressure_diffusion not optimized
add_linear not optimized


and then I changed the code as you suggested: mpirun -np 4 python TG.py --optimization cython VV
the output is
add_pressure_diffusion not optimized
add_linear not optimized
0.02 0.12499063 0.00000000e+00 5.46727837e-40
0.04 0.12498125 1.38777878e-17 1.10787480e-38
0.06 0.12497187 0.00000000e+00 1.17977406e-37
0.08 0.12496250 0.00000000e+00 2.79999540e-37
0.10 0.12495312 2.77555756e-17 8.14645107e-37
Time = 5.168408155441284
Fastest = (0.013711214065551758, 3.7706851959228516)
Slowest = (0.013721942901611328, 3.7706992626190186)
Memory usage                    RSS accum     RSS total   Virtual  Virtual total
End                                751 MB        751 MB      11724 MB      11724 MB
add_pressure_diffusion not optimized
add_linear not optimized
add_pressure_diffusion not optimized
add_linear not optimized
add_pressure_diffusion not optimized
add_linear not optimized

**Comment by xanfus** [comment]
Should one update demo section in README.md?
```
(spectralDNS) alpha@alpha-VirtualBox:~/spectralDNS/demo$ mpirun -np 1 python3 TG.py NS
/home/alpha/anaconda3/envs/spectralDNS/lib/python3.11/site-packages/shenfun/optimization/numba/chebyshev.py:22: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @jit
/home/alpha/anaconda3/envs/spectralDNS/lib/python3.11/site-packages/shenfun/optimization/numba/__init__.py:201: NumbaDeprecationWarning: The keyword argument 'nopython=False' was supplied. From Numba 0.59.0 the default is being changed to True and use of 'nopython=False' will raise a warning as the argument will have no effect. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @nb.jit(nopython=False, fastmath=True, cache=True)
begin
1
cross1 not optimized
cross2 not optimized
RK4 not optimized
ForwardEuler not optimized
AB2 not optimized
add_pressure_diffusion not optimized
2
3
4
5
0.02 0.12499063 -4.16333634e-17 6.30456069e-31
0.04 0.12498125 0.00000000e+00 6.27437434e-31
0.06 0.12497187 -2.77555756e-17 6.24441058e-31
0.08 0.12496250 -1.38777878e-17 6.21470240e-31
0.10 0.12495312 0.00000000e+00 6.18517193e-31
Time = 1.0339162349700928
Fastest = (0.01658153533935547, 0.276364803314209)
Slowest = (0.01658153533935547, 0.276364803314209)
Memory usage                    RSS accum     RSS total   Virtual  Virtual total
End                                244 MB        244 MB       1139 MB       1139 MB
[WARNING] yaksa: 4 leaked handle pool objects

(spectralDNS) alpha@alpha-VirtualBox:~/spectralDNS/demo$ python TG.py --optimization cython NS
/home/alpha/anaconda3/envs/spectralDNS/lib/python3.11/site-packages/shenfun/optimization/numba/chebyshev.py:22: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @jit
/home/alpha/anaconda3/envs/spectralDNS/lib/python3.11/site-packages/shenfun/optimization/numba/__init__.py:201: NumbaDeprecationWarning: The keyword argument 'nopython=False' was supplied. From Numba 0.59.0 the default is being changed to True and use of 'nopython=False' will raise a warning as the argument will have no effect. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @nb.jit(nopython=False, fastmath=True, cache=True)
begin
1
2
3
4
5
0.02 0.12499063 -4.16333634e-17 6.30455938e-31
0.04 0.12498125 0.00000000e+00 6.27437746e-31
0.06 0.12497187 -2.77555756e-17 6.24440014e-31
0.08 0.12496250 -1.38777878e-17 6.21468312e-31
0.10 0.12495312 0.00000000e+00 6.18515452e-31
Time = 1.033937692642212
Fastest = (0.013664722442626953, 0.2962381839752197)
Slowest = (0.013664722442626953, 0.2962381839752197)
Memory usage                    RSS accum     RSS total   Virtual  Virtual total
End                                244 MB        244 MB       1139 MB       1139 MB
[WARNING] yaksa: 4 leaked handle pool objects

(spectralDNS) alpha@alpha-VirtualBox:~/spectralDNS/demo$ mpirun -np 1 python TG.py --optimization cython NS
/home/alpha/anaconda3/envs/spectralDNS/lib/python3.11/site-packages/shenfun/optimization/numba/chebyshev.py:22: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @jit
/home/alpha/anaconda3/envs/spectralDNS/lib/python3.11/site-packages/shenfun/optimization/numba/__init__.py:201: NumbaDeprecationWarning: The keyword argument 'nopython=False' was supplied. From Numba 0.59.0 the default is being changed to True and use of 'nopython=False' will raise a warning as the argument will have no effect. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @nb.jit(nopython=False, fastmath=True, cache=True)
begin
1
2
3
4
5
0.02 0.12499063 -4.16333634e-17 6.30455938e-31
0.04 0.12498125 0.00000000e+00 6.27437746e-31
0.06 0.12497187 -2.77555756e-17 6.24440014e-31
0.08 0.12496250 -1.38777878e-17 6.21468312e-31
0.10 0.12495312 0.00000000e+00 6.18515452e-31
Time = 1.0515727996826172
Fastest = (0.013274669647216797, 0.26799511909484863)
Slowest = (0.013274669647216797, 0.26799511909484863)
Memory usage                    RSS accum     RSS total   Virtual  Virtual total
End                                244 MB        244 MB       1139 MB       1139 MB
[WARNING] yaksa: 4 leaked handle pool objects
```
