### ISSUE TITLE
Issue in Isotropic.py

### ISSUE THREAD

**Issue by msmerlak** [spectralDNS/spectralDNS#27]
I'm trying to run your code for isotropic turbulence, running into the following problem. It looks like the code is looking for a file on your local drive, I don't know how to change that. Thanks for your help.

(spectralDNS) mb024:demo smerlak$ python Isotropic.py NS
Isotropic.py:24: UserWarning: matplotlib not installed
  warnings.warn("matplotlib not installed")
cross1 not optimized
cross2 not optimized
RK4 not optimized
ForwardEuler not optimized
AB2 not optimized
add_pressure_diffusion not optimized
Traceback (most recent call last):
  File "Isotropic.py", line 385, in <module>
    init_from_file("NS_isotropic_6_6_6b.h5", sol, context)
  File "Isotropic.py", line 338, in init_from_file
    assert "1" in f["3D/checkpoint/U"]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/mikaelmortensen/anaconda2/conda-bld/osx-host_1490718644237/work/h5py-2.6.0/h5py/_objects.c:3195)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/mikaelmortensen/anaconda2/conda-bld/osx-host_1490718644237/work/h5py-2.6.0/h5py/_objects.c:3153)
  File "/anaconda3/envs/spectralDNS/lib/python3.6/site-packages/h5py/_hl/group.py", line 166, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/mikaelmortensen/anaconda2/conda-bld/osx-host_1490718644237/work/h5py-2.6.0/h5py/_objects.c:3195)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/mikaelmortensen/anaconda2/conda-bld/osx-host_1490718644237/work/h5py-2.6.0/h5py/_objects.c:3153)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/Users/mikaelmortensen/anaconda2/conda-bld/osx-host_1490718644237/work/h5py-2.6.0/h5py/h5o.c:4081)
KeyError: 'Unable to open object (Component not found)'

**Comment by mikaem** [comment]
Hi
You are correct, the demo as it stands is trying to restart from a previous simulation. Try to remove [line 385](https://github.com/spectralDNS/spectralDNS/blob/6c3ad9a598508fdf9911ed76007693693e38287d/demo/Isotropic.py#L385) and try again. It should then use a generic initialization routine, and will take some time to develop a steady spectrum.

**Comment by msmerlak** [comment]
I replaced `U` in line 308 by `c.U`, looks like it's working

**Comment by mikaem** [comment]
Hope it's working. I had this fixed locally, but had forgotten to push. Should be ok now, so closing.
