### ISSUE TITLE
pyFFTW Runtime Error

### ISSUE THREAD

**Issue by loiseaujc** [spectralDNS/spectralDNS#29]
Hej,

I have just downloaded the latest build available on conda and, whenever I try to run the channel flow, I get the following error: 

`RuntimeError: The data has an uncaught error that led to the planner returning NULL. This is a bug.`

I made sure to download pyfftw directly from your channel as to avoid the missing dct problem.

For the sake of completeness, below is the whole message that gets printed whenver I try to run the LaminarChannel.py file.

`Traceback (most recent call last):
  File "LaminarChannel.py", line 133, in <module>
    context = solver.get_context()
  File "/home/jean-christophe/anaconda3/envs/spectralDNS/lib/python3.6/site-packages/spectralDNS/solvers/KMM.py", line 31, in get_context
    FST = TensorProductSpace(comm, (ST, K0, K1), **{'threads':params.threads, 'planner_effort':params.planner_effort["dct"]})    # Dirichlet
  File "/home/jean-christophe/anaconda3/envs/spectralDNS/lib/python3.6/site-packages/shenfun/tensorproductspace.py", line 102, in __init__
    self.xfftn[-1].plan(pencil.subshape, axes, dtype, kw)
  File "/home/jean-christophe/anaconda3/envs/spectralDNS/lib/python3.6/site-packages/shenfun/spectralbase.py", line 543, in plan
    xfftn_fwd = plan_fwd(U, n=n, axis=axis, **opts)
  File "/home/jean-christophe/anaconda3/envs/spectralDNS/lib/python3.6/site-packages/pyfftw/builders/builders.py", line 410, in rfft
    avoid_copy, inverse, real)
  File "/home/jean-christophe/anaconda3/envs/spectralDNS/lib/python3.6/site-packages/pyfftw/builders/_utils.py", line 205, in _Xfftn
    flags, threads)
  File "pyfftw/pyfftw.pyx", line 1252, in pyfftw.pyfftw.FFTW.__cinit__ (/home/mikael/anaconda2/conda-bld/pyfftw_1486478882857/work/pyfftw/pyfftw.c:11622)
RuntimeError: The data has an uncaught error that led to the planner returning NULL. This is a bug.
`

**Comment by mikaem** [comment]
Hej

Thanks a lot for bringing the LaminarChannel to my attention. I had forgotten to fix it after a recent change to [shenfun](https://github.com/spectralDNS/shenfun). The error you're seeing, though, is highly likely a pyfftw bug. I believe it can be fixed by importing pyfftw before numpy. Can you try to add import pyfftw on the line prior to import numpy as np as see if that fixes it? I cannot reproduce the error, so no way for me to check. 

Oh, and for LaminarChannel to give the correct results you need to delete line 22 (Sk[1] /= (4*np.pi**2)
) This will be fixed in master very soon.
