### ISSUE TITLE
ModuleNotFoundError: No module named 'spectralDNS'

### ISSUE THREAD

**Issue by shangwenqiang** [spectralDNS/spectralDNS#33]
When I ran the demo case using command 'mpirun -np 4 python TG.py NS', the error occurred. However, I have configured the enviroment according to the tutorial written in the github. How can I solve these problem?

**Comment by mikaem** [comment]
Hi
Seems like you just need to put the installed spectralDNS on the PYTHONPATH. In the terminal do something like

`export PYTHONPATH=/path to spectralDNS/:$PYTHONPATH`

**Comment by francispoulin** [comment]
I am getting a similar yet slightly different error, copied below, after having installed spectralDNS using conda and trying to run the first line, as above.

It's similar because there is a ModuleNotFoundError, but differs because mpi4py_fft.utilities is what's not found.  Because I used conda I didn't think I would need to change my PYTHONPATH but if that's necessary it is easily done.  

Is that what I should do or is it another problem?

`(spectralDNS) fpoulin@amlt21:~/software/learningDNS/demo$ mpirun -np 1 python TG.py NS
Traceback (most recent call last):
  File "TG.py", line 144, in <module>
    mesh="triplyperiodic")
  File "/home/fpoulin/software/anaconda3/envs/spectralDNS/lib/python3.6/site-packages/spectralDNS/__init__.py", line 50, in get_solver
    config.params.solver)))
  File "/home/fpoulin/software/anaconda3/envs/spectralDNS/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fpoulin/software/anaconda3/envs/spectralDNS/lib/python3.6/site-packages/spectralDNS/solvers/NS.py", line 8, in <module>
    from shenfun import Basis, TensorProductSpace, VectorTensorProductSpace, \
  File "/home/fpoulin/software/anaconda3/envs/spectralDNS/lib/python3.6/site-packages/shenfun/__init__.py", line 38, in <module>
    from .io import *
  File "/home/fpoulin/software/anaconda3/envs/spectralDNS/lib/python3.6/site-packages/shenfun/io/__init__.py", line 1, in <module>
    from .h5py_file import HDF5File
  File "/home/fpoulin/software/anaconda3/envs/spectralDNS/lib/python3.6/site-packages/shenfun/io/h5py_file.py", line 3, in <module>
    from mpi4py_fft.utilities import HDF5File as BaseFile
ModuleNotFoundError: No module named 'mpi4py_fft.utilities'
`

**Comment by thw1021** [comment]
@francispoulin 
Hi Francis J. Poulin, I got same error. Have you solved it ?

**Comment by francispoulin** [comment]
Yes, when i set the pythonpath it did work as @mikaem suggested.
I hope it works well for you too.

**Comment by thw1021** [comment]
@francispoulin Thank you. I have ever tried to set the pythonpath but it didn't work. Maybe I did something wrong.
Can you make sure the following steps are right ?
1. set the pythonpath by adding `export PYTHONPATH="$HOME/spectralDNS/install:$PYTHONPATH"` to `.bashrc` file.
2. `cd ~/spectralDNS/`
3. install spectralDNS by `python setup.py install --prefix=./install/`

**Comment by francispoulin** [comment]
Unfortuantely, I don't understand the set up well enough to comment on why what you tried didn't work.  Sorry.

**Comment by thw1021** [comment]
Anyway, thank you. I may try it later again to see the results. Thank you.

**Comment by Daniel-J123** [comment]
@thw1021 hi ,I  now have got the same problem, when I use your way to try to solve it ,but no use!
so i want to ask you how to solve it in details???? thank you!!!

**Comment by thw1021** [comment]
@Daniel-J123 Hi, I am sorry for the late reply. To be honest, I do not quite understand this problem (something changed so I do not dig into the code).  
Have you ever tried [these steps ](https://github.com/spectralDNS/spectralDNS/issues/33#issuecomment-632101332) and update the code to the latest ?
BTW, I run the code using docker. In this way, I can avoid possible problems due to system environment.

**Comment by Daniel-J123** [comment]
@thw1021 yes I have solved this problem ,but after that when I run some demos like `mpirun -np 8 python TG.py NS`,here something occurs,
![图片](https://user-images.githubusercontent.com/66522801/93954548-8ce9df80-fd80-11ea-86d1-9cd5e592d946.png)
do you know what's wrong?? so anxious am I  !!

**Comment by thw1021** [comment]
@Daniel-J123 
Looks like there is something wrong with your `mpi` setting.  Not a specialist about this.

**Comment by Daniel-J123** [comment]
@thw1021 thank you ! I solved it !
