### ISSUE TITLE
Unable to compile spectralDNS using conda build

### ISSUE THREAD

**Issue by anubhavd91** [spectralDNS/spectralDNS#34]
I am unable to compile spectralDNS using conda build. 
After using: 
conda build -c conda-forge conf/conda
I run into the following error: 

  Build:
source activate  /project/dwive016/opt/Anaconda_3/conda-bld/_build_env 

Traceback (most recent call last):
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda_build/environ.py", line 756, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda/plan.py", line 473, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda/core/solve.py", line 107, in solve_for_transaction
    force_remove, force_reinstall)
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda/core/solve.py", line 145, in solve_for_diff
    force_remove)
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda/core/solve.py", line 242, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda/core/solve.py", line 510, in _run_sat
    ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs))
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda/resolve.py", line 1054, in solve
    self.find_conflicts(specs)
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda/resolve.py", line 316, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - mpich[version='>=3.3.2,<3.4.0a0']
  - python[version='>=3.7,<3.8.0a0']
  - shenfun[version='>=2.0.8']
Use "conda search <package> --info" to see the dependencies for each package.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/dwive016/opt/Anaconda_3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda_build/build.py", line 2343, in build_tree
    notest=notest,
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda_build/build.py", line 1407, in build
    create_build_envs(top_level_pkg, notest)
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda_build/build.py", line 1291, in create_build_envs
    raise e
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda_build/build.py", line 1281, in create_build_envs
    channel_urls=tuple(m.config.channel_urls))
  File "/project/dwive016/opt/Anaconda_3/lib/python3.7/site-packages/conda_build/environ.py", line 758, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"shenfun[version='>=2.0.8']", "python[version='>=3.7,<3.8.0a0']", "mpich[version='>=3.3.2,<3.4.0a0']"}

When I try, 
conda search shenfun --info

Loading channels: done
No match found for: shenfun. Search: *shenfun*

PackagesNotFoundError: The following packages are not available from current channels:

  - shenfun

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

I am new to using python, but any help in figuring this problem would be extremely helpful.

**Comment by mikaem** [comment]
Hi
Looks like you have some compatibility issues in your conda environment. Could you please try to create a fresh environment using the following:

`conda create --name spectralDNS -c conda-forge shenfun mpi4py-fft cython numba pythran mpich pip h5py=*=mpi*
conda activate spectralDNS
`
and then just simply from the folder where you have the spectralDNS software (the directory where setup.py is located)

`python setup.py build_ext -i`

and add the install directory to the PYTHONPATH.

**Comment by anubhavd91** [comment]
Hi, 

Thanks for your response. 
I tried creating fresh environment:

conda create --name spectralDNS -c conda-forge shenfun mpi4py-fft cython numba pythran mpich pip h5py=*=mpi* conda activate spectralDNS
source: No match.

I notice that when I remove h5py=*=mpi*, the new environment is created.

**Comment by mikaem** [comment]
Sorry, that should be two commands, first

`conda create --name spectralDNS -c conda-forge shenfun mpi4py-fft cython numba pythran mpich pip h5py=*=mpi*`
and then
`conda activate spectralDNS `

**Comment by anubhavd91** [comment]
Hi, 
Tried it. Same problem 
conda create --name spectralDNS -c conda-forge shenfun mpi4py-fft cython numba pythran mpich pip h5py=\*=mpi\*
source: No match.
If I just try
 pip h5py=\*=mpi\*
 pip: No match

**Comment by mikaem** [comment]
pip will not work like that, see [docs for h5py](http://docs.h5py.org/en/stable/build.html). Can you create the environment without shenfun, mpi4py-fft and h5py?

**Comment by anubhavd91** [comment]
Hi, 

I can create the environment without shenfun, mpi4py-fft and h5py

**Comment by mikaem** [comment]
With h5py?

**Comment by anubhavd91** [comment]
yes, this works:
conda create --name spectralDNS -c conda-forge cython numba pythran mpich h5py

**Comment by mikaem** [comment]
Does it install parallel h5py? You can check with `conda list` inside the new environment?

**Comment by anubhavd91** [comment]
No not parallel h5py. Here is the output:

# packages in environment at /project/dwive016/opt/Anaconda_3/envs/spectralDNS:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
beniget                   0.2.0                      py_0    conda-forge
binutils_impl_linux-64    2.33.1               he1b5a44_7    conda-forge
binutils_linux-64         2.33.1              h9595d00_15    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cython                    0.29.14          py37he1b5a44_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
gast                      0.3.2                      py_0    conda-forge
gcc_impl_linux-64         7.3.0                habb00fd_2    conda-forge
gcc_linux-64              7.3.0               h553295d_15    conda-forge
gxx_impl_linux-64         7.3.0                hdf63c60_2    conda-forge
gxx_linux-64              7.3.0               h553295d_15    conda-forge
h5py                      2.10.0          nompi_py37h513d04c_100    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                hdf63c60_0    conda-forge
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libopenblas               0.3.7                h5ec1e0e_4    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_0    conda-forge
llvmlite                  0.30.0           py37h8b12597_1    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.3.2                hc856adb_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                        py_0    conda-forge
numba                     0.46.0           py37hb3f55d8_1    conda-forge
numpy                     1.17.3           py37h95a1406_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pip                       19.3.1                   py37_0    conda-forge
ply                       3.11                       py_1    conda-forge
python                    3.7.3                h357f687_2    conda-forge
pythran                   0.9.4.post1      py37hc9558a2_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                42.0.2                   py37_0    conda-forge
six                       1.13.0                   py37_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xsimd                     7.2.2                hc9558a2_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge

**Comment by mikaem** [comment]
Yes, you need to use the `h5py=*=mpi*`. But that's where it fails, right?

**Comment by anubhavd91** [comment]
Yes. Thats when I get the "source: No match" prompt.

**Comment by mikaem** [comment]
How about `conda install h5py=2.10.*=mpi_mpich`?

**Comment by anubhavd91** [comment]
Same issue

**Comment by mikaem** [comment]
Have you added `conda-forge` to the list of channels to search?

**Comment by mikaem** [comment]
Otherwise you need to use `-c conda-forge`

**Comment by anubhavd91** [comment]
conda install h5py=2.10.*=mpi_mpich -c conda-forge
source: No match

**Comment by mikaem** [comment]
I think it needs to be `conda install -c conda-forge h5py=2.10.*=mpi_mpich`

**Comment by anubhavd91** [comment]
same issue
conda install -c conda-forge h5py=2.10.*=mpi_mpich
source: No match.

**Comment by anubhavd91** [comment]
same issue
conda install -c conda-forge h5py=2.10.\*=mpi_mpich
source: No match.

**Comment by mikaem** [comment]
Sorry, needs to have the asterix `*` there at the end

`conda install -c conda-forge h5py=2.10.*=mpi_mpich*`

or 

`conda install -c conda-forge h5py=2.10.*=mpi*`

 You could also try to add conda-forge to .condarc and then skip using `-c conda-forge`

`conda config --add channels conda-forge`

**Comment by lnista** [comment]
Hello, 

I followed your suggestions. I first created and activated a fresh conda environment with no issues:

`conda create --name spectralDNS -c conda-forge shenfun mpi4py-fft cython numba pythran mpich pip h5py=*=mpi*`
`conda activate spectralDNS`

When I move to the main folder spectralDNS, as suggested, I executed: 
`conda build -c conda-forge conf/conda`

but the following issue occurred during the test session for 5 different files:
`ImportError while importing test module '$SRC_DIR/tests/test_MHD.py'. ModuleNotFoundError: No module named 'six'`
and 
`ImportError while importing test module '$SRC_DIR/tests/test_shentransforms.py'. ModuleNotFoundError: No module named 'spectralDNS.shen.LUsolve'`

Could you please help me with this issue?
Thank you in advance!

**Comment by mikaem** [comment]
Hi
There is really no need to use conda build if you already have a good environment. Try 

    python setup.py build_ext -i

instead. And make sure spectralDNS is on the PYTHONPATH.

**Comment by lnista** [comment]
> setup.py build_ext -i

Unfortunately, I received a series of errors starting with:
`fatal error: cblas.h: No such file or directory`. It seems there is something missing with C++. spectralDNS is on the PYTHONPATH.

**Comment by mikaem** [comment]
Are you on ubuntu? I think maybe you need to us conda compilers. Could you try

    conda install -c conda-forge compilers

and then try setup again?

**Comment by lnista** [comment]
I am using: `CentOS Linux release 8.2.2004`.
Even if I  installed the required compilers, I got the same error.

**Comment by wangicewing** [comment]
hello,  I am unable to compile spectralDNS using conda build on MAC.
After using:  conda create --name spectralDNS -c conda-forge shenfun mpi4py-fft cython numba pythran mpich pip h5py=*=mpi*

I run into the following error:
    zsh: no matches found: h5py=2.10.*=mpi_mpich*

**Comment by wangicewing** [comment]
hello, I am unable to compile spectralDNS using conda build on MAC.
After using: conda create --name spectralDNS -c conda-forge shenfun mpi4py-fft cython numba pythran mpich pip h5py=*=mpi*

I run into the following error:
zsh: no matches found: h5py=*=mpi*

**Comment by wangicewing** [comment]
hello, I am unable to compile spectralDNS using conda build on MAC.
After using: 
`conda create --name spectralDNS -c conda-forge shenfun mpi4py-fft cython numba pythran mpich pip h5py=*=mpi*`
I run into the following error:
`no matches found: h5py=*=mpi*`

**Comment by florianradack** [comment]
Has there been any progress on this issue? I am still experiencing the above issues.
