### ISSUE TITLE
AttributeError: 'QuadContourSet' object has no attribute 'ax'

### ISSUE THREAD

**Issue by xanfus** [spectralDNS/spectralDNS#54]
Class definition tells, QCS has 'ax'. Matplotlib is 3.7.2, both conda and pypi.
```
(spectralDNS) alpha@alpha-VirtualBox:~/spectralDNS/demo$ mpirun -np 1 python3 TG.py NS
/home/alpha/anaconda3/envs/spectralDNS/lib/python3.11/site-packages/shenfun/optimization/numba/chebyshev.py:22: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @jit
/home/alpha/anaconda3/envs/spectralDNS/lib/python3.11/site-packages/shenfun/optimization/numba/__init__.py:201: NumbaDeprecationWarning: The keyword argument 'nopython=False' was supplied. From Numba 0.59.0 the default is being changed to True and use of 'nopython=False' will raise a warning as the argument will have no effect. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @nb.jit(nopython=False, fastmath=True, cache=True)
cross1 not optimized
cross2 not optimized
RK4 not optimized
ForwardEuler not optimized
AB2 not optimized
add_pressure_diffusion not optimized
0.02 0.12499063 -4.16333634e-17 6.30456069e-31
Traceback (most recent call last):
  File "/home/alpha/spectralDNS/demo/TG.py", line 161, in <module>
    solve(sol, context)
  File "/home/alpha/spectralDNS/spectralDNS/__init__.py", line 101, in solve
    solver.update(context)
  File "/home/alpha/spectralDNS/demo/TG.py", line 64, in update
    im1.ax.clear()
    ^^^^^^
AttributeError: 'QuadContourSet' object has no attribute 'ax'
[WARNING] yaksa: 4 leaked handle pool objects
```

**Comment by xanfus** [comment]
I've replaced 'ax' for 'axes'.
