### ISSUE TITLE
ValueError: Unable to synchronously create dataset (no write intent on file)

### ISSUE THREAD

**Issue by xanfus** [spectralDNS/spectralDNS#56]
Error occurs at 1.8<_T_<2.0 independently from _np_.
```
mpirun -np 1 python Isotropic.py --optimization cython NS
/home/alpha/anaconda3/envs/spectralDNS/lib/python3.11/site-packages/shenfun/optimization/numba/chebyshev.py:22: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @jit
/home/alpha/anaconda3/envs/spectralDNS/lib/python3.11/site-packages/shenfun/optimization/numba/__init__.py:201: NumbaDeprecationWarning: The keyword argument 'nopython=False' was supplied. From Numba 0.59.0 the default is being changed to True and use of 'nopython=False' will raise a warning as the argument will have no effect. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @nb.jit(nopython=False, fastmath=True, cache=True)
spectralDNS.solvers.NS
0.2000 4.794113e+00 4.794113e+00 3.669030e+00 3.669030e+00 -3.669030e+00 3.681857e+00 4.385344e+01 8.400000e+01
0.4000 4.794113e+00 4.794113e+00 2.004871e+00 2.004871e+00 -2.004871e+00 2.009544e+00 5.932477e+01 8.400000e+01
0.6000 4.794113e+00 4.794113e+00 1.402259e+00 1.402259e+00 -1.402259e+00 1.403908e+00 7.093576e+01 8.400000e+01
0.8000 4.794113e+00 4.794113e+00 1.195115e+00 1.195115e+00 -1.195115e+00 1.195590e+00 7.683770e+01 8.400000e+01
1.0000 4.794113e+00 4.794113e+00 1.135622e+00 1.135622e+00 -1.135622e+00 1.135694e+00 7.882469e+01 8.400000e+01
1.2000 4.794113e+00 4.794113e+00 1.129659e+00 1.129659e+00 -1.129659e+00 1.129579e+00 7.903249e+01 8.400000e+01
1.4000 4.794113e+00 4.794113e+00 1.134295e+00 1.134295e+00 -1.134295e+00 1.134192e+00 7.887081e+01 8.400000e+01
1.6000 4.794113e+00 4.794113e+00 1.149122e+00 1.149122e+00 -1.149122e+00 1.148949e+00 7.836031e+01 8.400000e+01
1.8000 4.794113e+00 4.794113e+00 1.176500e+00 1.176500e+00 -1.176500e+00 1.176333e+00 7.744321e+01 8.400000e+01
Traceback (most recent call last):
  File "/home/alpha/modeling/sDNS/Isotropic.py", line 321, in <module>
    solve(sol, context)
  File "/home/alpha/spectralDNS/spectralDNS/__init__.py", line 102, in solve
    solver.update(context)
  File "/home/alpha/modeling/sDNS/Isotropic.py", line 217, in update
    f['Turbulence/Ek'].create_dataset(str(params.tstep), data=Ek)
  File "/home/alpha/anaconda3/envs/spectralDNS/lib/python3.11/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alpha/anaconda3/envs/spectralDNS/lib/python3.11/site-packages/h5py/_hl/dataset.py", line 163, in make_new_dset
    dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl, dapl=dapl)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 138, in h5py.h5d.create
ValueError: Unable to synchronously create dataset (no write intent on file)
[WARNING] yaksa: 8 leaked handle pool objects
```

**Comment by xanfus** [comment]
What does your `h5cc -showconfig` return?
```
(base) alpha@alpha-VirtualBox:~$ h5cc -showconfig | grep Parallel
                   Parallel HDF5: no
Parallel Filtered Dataset Writes: no
              Large Parallel I/O: no
```

**Comment by xanfus** [comment]
```
(spectralDNS) alpha@alpha-VirtualBox:~$ h5pcc -showconfig
	    SUMMARY OF THE HDF5 CONFIGURATION
	    =================================

General Information:
-------------------
		   HDF5 Version: 1.8.17
		  Configured on: Tue Nov 14 09:51:09 CET 2017
		  Configured by: mikael@ubuntu
		 Configure mode: production
		    Host system: x86_64-unknown-linux-gnu
	      Uname information: Linux ubuntu 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
		       Byte sex: little-endian
		      Libraries: static, shared
	     Installation point: /home/alpha/anaconda3/envs/spectralDNS

Compiling Options:
------------------
               Compilation Mode: production
                     C Compiler: /home/alpha/anaconda3/envs/spectralDNS/bin/mpicc ( MPICH version 3.2 Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu built with gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4))
                         CFLAGS: -w
                      H5_CFLAGS: -std=c99 -pedantic -Wall -Wextra -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline -Wfloat-equal -Wmissing-format-attribute -Wmissing-noreturn -Wpacked -Wdisabled-optimization -Wformat=2 -Wunreachable-code -Wendif-labels -Wdeclaration-after-statement -Wold-style-definition -Winvalid-pch -Wvariadic-macros -Winit-self -Wmissing-include-dirs -Wswitch-default -Wswitch-enum -Wunused-macros -Wunsafe-loop-optimizations -Wc++-compat -Wstrict-overflow -Wlogical-op -Wlarger-than=2048 -Wvla -Wsync-nand -Wframe-larger-than=16384 -Wpacked-bitfield-compat -Wstrict-overflow=5 -Wjump-misses-init -Wunsuffixed-float-constants -Wdouble-promotion -Wsuggest-attribute=const -Wtrampolines -Wstack-usage=8192 -Wvector-operation-performance -Wsuggest-attribute=pure -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -Wdate-time -Wopenmp-simd -Warray-bounds=2 -Wc99-c11-compat -O3 -fstdarg-opt
                      AM_CFLAGS: 
                       CPPFLAGS: 
                    H5_CPPFLAGS: -D_GNU_SOURCE -D_POSIX_C_SOURCE=200112L   -DNDEBUG -UH5_DEBUG_API
                    AM_CPPFLAGS:  -I/home/alpha/anaconda3/envs/spectralDNS/include
               Shared C Library: yes
               Static C Library: yes
  Statically Linked Executables: no
                        LDFLAGS: 
                     H5_LDFLAGS: 
                     AM_LDFLAGS:  -L/home/alpha/anaconda3/envs/spectralDNS/lib
 	 	Extra libraries: -lz -ldl -lm 
 		       Archiver: ar
 		 	 Ranlib: ranlib
 	      Debugged Packages: 
		    API Tracing: no

Languages:
----------
                        Fortran: no

                            C++: no

Features:
---------
                  Parallel HDF5: yes
             High Level library: yes
                   Threadsafety: no
            Default API Mapping: v18
 With Deprecated Public Symbols: yes
         I/O filters (external): deflate(zlib)
                            MPE: 
                     Direct VFD: no
                        dmalloc: no
Clear file buffers before write: yes
           Using memory checker: no
         Function Stack Tracing: no
      Strict File Format Checks: no
   Optimization Instrumentation: no
(spectralDNS) alpha@alpha-VirtualBox:~$ 

```

**Comment by my-Pluto** [comment]
Hello, 
I encountered the same problem while running this project. May I ask how you solved this problem? 
Thank you very much.

**Comment by xanfus** [comment]
> Hello, I encountered the same problem while running this project. May I ask how you solved this problem? Thank you very much.

I've commented out the problematic line 217 of Isotropic.py and everything else uninteresting to me in _update()_.
