### ISSUE TITLE
Installing using Conda

### ISSUE THREAD

**Issue by cwoolfo1** [spectralDNS/spectralDNS#67]
I am having issues installing this solver. It appears that Cython is having problems compiling the cython files. Does anyone have a fix for this?

Here is what I ran
```
conda create --name spectralDNS -c conda-forge shenfun mpi4py-fft cython numba pythran mpich pip h5py=*=mpi*
conda activate spectralDNS
python setup.py build_ext -i
```

And here is the error that I am having
```
 dist.fetch_build_eggs(dist.setup_requires)
running build_ext
Compiling /Documents/spectralDNS/spectralDNS/shen/LUsolve.pyx because it changed.
[1/1] Cythonizing /Documents/spectralDNS/spectralDNS/shen/LUsolve.pyx
/miniconda3/envs/spectralDNS/lib/python3.12/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /Documents/spectralDNS/spectralDNS/shen/LUsolve.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
ctypedef fused T:
    real_t
    complex_t


def Mult_Div_3D(np.int_t N,
                ^
------------------------------------------------------------

spectralDNS/shen/LUsolve.pyx:20:16: 'int_t' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
                        u_hat[:, i, j],
                        v_hat[:, i, j],
                        w_hat[:, i, j],
                        b[:, i, j])

def Mult_Div_1D(np.int_t N,
                ^
------------------------------------------------------------

spectralDNS/shen/LUsolve.pyx:37:16: 'int_t' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    sum_u0 += v_hat[st]
    bv[0] = -sum_u0*2
    sum_u2 += w_hat[st]
    bw[0] = -sum_u2*2

def Mult_CTD_3D_ptr(np.int_t N,
                    ^
------------------------------------------------------------

spectralDNS/shen/LUsolve.pyx:162:20: 'int_t' is not a type identifier
Traceback (most recent call last):
  File "/Documents/spectralDNS/setup.py", line 67, in <module>
    setup(name="spectralDNS",
  File "/miniconda3/envs/spectralDNS/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda3/envs/spectralDNS/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 183, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/miniconda3/envs/spectralDNS/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
    dist.run_commands()
  File "/miniconda3/envs/spectralDNS/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "/miniconda3/envs/spectralDNS/lib/python3.12/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/miniconda3/envs/spectralDNS/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/miniconda3/envs/spectralDNS/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 98, in run
    _build_ext.run(self)
  File "/miniconda3/envs/spectralDNS/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/Documents/spectralDNS/setup.py", line 34, in build_extensions
    build_ext.build_extensions(self)
  File "/miniconda3/envs/spectralDNS/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
    self._build_extensions_serial()
  File "/miniconda3/envs/spectralDNS/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
    self.build_extension(ext)
  File "/miniconda3/envs/spectralDNS/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
    _build_ext.build_extension(self, ext)
  File "/miniconda3/envs/spectralDNS/lib/python3.12/site-packages/Cython/Distutils/build_ext.py", line 130, in build_extension
    new_ext = cythonize(
              ^^^^^^^^^^
  File "/miniconda3/envs/spectralDNS/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "/miniconda3/envs/spectralDNS/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /Documents/spectralDNS/spectralDNS/shen/LUsolve.pyx
```

**Comment by ctowery** [comment]
I had the same issue just now. Googling around, I figured out that Numpy 2.0+ has deprecated the numpy.int_t type, and it no longer exists. With Conda you can revert to Numpy 1.26 via
`conda -c conda-forge install numpy=1.26.4`
and then it will compile.

**Comment by alessandrogentili001** [comment]
yeah, you're right. Just to add a small thing: in my case your command does not work, I used `
conda install -c conda-forge numpy=1.26.4
` instead.
